# Generated by Django 2.2.6 on 2019-11-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
