# Generated by Django 2.2.6 on 2019-11-14 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_leadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company',
            field=models.CharField(choices=[('ttu', 'TTU')], default='TTU', max_length=6),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(help_text='Only digits allowed', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 10 digits allowed.', regex='^\\d{9,15}$')], verbose_name='Phone number'),
        ),
    ]
