# Generated by Django 2.2.6 on 2019-11-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191114_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='venue',
        ),
    ]
